<a href="https://colab.research.google.com/github/simoncardenas2002/Redes-Neuronales/blob/master/dims_reshape.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [5]:
x=np.array([42,3,5,6,7,2,4,6])
print(x.shape)
x.ndim

(8,)


1

In [7]:
x=np.array([[42,3,5,6,7,2,4,6]
            ,[66,3,5,6,7,3,5,6]])
print(x.shape)
x.ndim

(2, 8)


2

In [9]:
x=np.array([[[42,3,5,6,7,2,4,6]
            ,[66,3,5,6,7,3,5,6]],[[42,3,5,6,7,2,4,6]
            ,[66,3,5,6,7,3,5,6]],[[42,3,5,6,7,2,4,6]
            ,[66,3,5,6,7,3,5,6]]])
print(x.shape)
x.ndim

(3, 2, 8)


3

Reshape:

In [17]:
x=np.array([[0,1],
         [2,3],
         [4,5],
         [6,7],
         [8,9]]
         )
x.shape

(5, 2)

In [18]:
x.reshape(10,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [19]:
x.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [21]:
#Transpuesta
x.T

array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])